"""
Static reference data for the East Africa Security Dashboard.

INCIDENTS and COUNTRIES are now generated automatically each pipeline run
from live scraped data. Only SOCIAL_MONITORS (X account lists) and
COUNTRY_META (flags, default sources) are kept here.
"""

# ── Country metadata (static — flags, ids, default sources) ───────────────────
COUNTRY_META = [
    {
        "id":   "sudan",
        "name": "Sudan",
        "flag": "🇸🇩",
        "defaultSources": [
            {"name": "Sudan War Monitor",  "url": "https://sudanwarmonitor.com"},
            {"name": "Sudan Tribune",      "url": "https://sudantribune.com"},
            {"name": "Sudans Post",        "url": "https://www.sudanspost.com"},
            {"name": "Dabanga Sudan",      "url": "https://www.dabangasudan.org/en"},
            {"name": "Nuba Reports",       "url": "https://nubareports.org"},
            {"name": "The New Humanitarian", "url": "https://www.thenewhumanitarian.org/africa/east-africa/sudan"},
            {"name": "BBC Sudan",          "url": "https://www.bbc.com/news/topics/cq23pdgvgm8t"},
            {"name": "ReliefWeb",          "url": "https://reliefweb.int"},
        ],
    },
    {
        "id":   "southsudan",
        "name": "South Sudan",
        "flag": "🇸🇸",
        "defaultSources": [
            {"name": "Radio Tamazuj",       "url": "https://radiotamazuj.org"},
            {"name": "Sudans Post",         "url": "https://www.sudanspost.com"},
            {"name": "Eye Radio",           "url": "https://www.eyeradio.org"},
            {"name": "Pachodo",             "url": "https://pachodo.org/news-from-various-sources"},
            {"name": "The Africa Report – South Sudan", "url": "https://www.theafricareport.com/country/south-sudan/"},
        ],
    },
    {
        "id":   "drc",
        "name": "DRC",
        "flag": "🇨🇩",
        "defaultSources": [
            {"name": "Radio Okapi",         "url": "https://www.radiookapi.net"},
            {"name": "MONUSCO",             "url": "https://monusco.unmissions.org"},
            {"name": "The Africa Report",   "url": "https://www.theafricareport.com/country/democratic-republic-of-congo/"},
            {"name": "Afrik.com RDC",       "url": "https://www.afrik.com/rdc"},
        ],
    },
    {
        "id":   "somalia",
        "name": "Somalia",
        "flag": "🇸🇴",
        "defaultSources": [
            {"name": "Somali Guardian", "url": "https://www.somaliguardian.com"},
            {"name": "Horseed Media",   "url": "https://horseedmedia.net"},
            {"name": "SONNA Somalia",   "url": "https://sonna.so/en/"},
        ],
    },
    {
        "id":   "ethiopia",
        "name": "Ethiopia",
        "flag": "🇪🇹",
        "defaultSources": [
            {"name": "Addis Standard",        "url": "https://addisstandard.com"},
            {"name": "The Reporter Ethiopia", "url": "https://www.thereporterethiopia.com"},
            {"name": "CFR – Ethiopia",        "url": "https://www.cfr.org/global-conflict-tracker/conflict/conflict-ethiopia"},
            {"name": "Ethiopia Observer",     "url": "https://www.ethiopiaobserver.com"},
            {"name": "The Africa Report – Ethiopia", "url": "https://www.theafricareport.com/country/ethiopia/"},
            {"name": "Borkena",               "url": "https://borkena.com"},
            {"name": "Ethiopia Insight",      "url": "https://www.ethiopia-insight.com"},
            {"name": "Ethiopian Monitor",     "url": "https://ethiopianmonitor.com"},
        ],
    },
]

# ── Social media monitors (X accounts per country) ────────────────────────────
SOCIAL_MONITORS = {
    "Sudan": {
        "x": [
            {"handle": "@sudan_war",      "url": "https://x.com/sudan_war",      "type": "Conflict Monitor", "desc": "Sudan War Monitor — real-time SAF/RSF battle maps and strike updates"},
            {"handle": "@thesudantimes",  "url": "https://x.com/thesudantimes",  "type": "Press",            "desc": "The Sudan Times — English-language breaking Sudan news"},
            {"handle": "@Sudan_tweet",    "url": "https://x.com/Sudan_tweet",    "type": "Press",            "desc": "Sudan news aggregator — crowd-sourced field reports"},
            {"handle": "@Reuters",        "url": "https://x.com/Reuters",        "type": "Press",            "desc": "Reuters wire — verified Sudan conflict breaking news"},
            {"handle": "@24Darfur",       "url": "https://x.com/24Darfur",       "type": "Conflict Monitor", "desc": "24 Darfur — RSF/SAF operations and Darfur atrocities tracking"},
            {"handle": "@SudanPlusNews",  "url": "https://x.com/SudanPlusNews",  "type": "Press",            "desc": "Sudan Plus News — breaking Sudan field updates"},
            {"handle": "@SudanTribune",   "url": "https://x.com/SudanTribune",   "type": "Press",            "desc": "Sudan Tribune — independent Sudan reporting (X feed)"},
            {"handle": "@martinplaut",    "url": "https://x.com/martinplaut",    "type": "Analyst",          "desc": "Martin Plaut — Horn of Africa journalist and analyst"},
        ],
        "instagram": [],
        "hashtags": ["#SudanWar", "#Khartoum", "#RSF", "#SAF", "#SudanCrisis", "#DarfurGenocide"],
        "searchTerms": ["Khartoum drone strike", "RSF Sudan attack", "SAF offensive", "Sudan UAE Ethiopia"],
    },
    "South Sudan": {
        "x": [
            {"handle": "@SouthSudanNews6", "url": "https://x.com/SouthSudanNews6", "type": "Press",    "desc": "South Sudan News — breaking field reports and conflict updates"},
            {"handle": "@SSGglobal",       "url": "https://x.com/SSGglobal",       "type": "Government","desc": "South Sudan Government global communications channel"},
            {"handle": "@ssemtv",          "url": "https://x.com/ssemtv",          "type": "Press",    "desc": "SSEM TV — South Sudan broadcast news and live reporting"},
            {"handle": "@MSF_SouthSudan",  "url": "https://x.com/MSF_SouthSudan",  "type": "NGO / UN",   "desc": "MSF South Sudan — humanitarian medical operations and alerts"},
            {"handle": "@SSudanNews",      "url": "https://x.com/SSudanNews",      "type": "Press",      "desc": "South Sudan News — independent breaking updates"},
            {"handle": "@EyeRadioJuba",    "url": "https://x.com/EyeRadioJuba",    "type": "Press",      "desc": "Eye Radio Juba — Juba-based broadcaster covering security and politics"},
            {"handle": "@SouthSudanGov",   "url": "https://x.com/SouthSudanGov",   "type": "Government", "desc": "South Sudan Government official communications"},
            {"handle": "@PonnieSheila",    "url": "https://x.com/PonnieSheila",    "type": "Analyst",    "desc": "Ponnie Sheila — South Sudan field reporting and commentary"},
        ],
        "instagram": [],
        "hashtags": ["#SouthSudan", "#Jonglei", "#SSPDF", "#SouthSudanCrisis", "#RJMEC"],
        "searchTerms": ["South Sudan Jonglei offensive", "SSPDF militia", "South Sudan displacement", "Machar trial"],
    },
    "DRC": {
        "x": [
            {"handle": "@BreakingN_RDC", "url": "https://x.com/BreakingN_RDC", "type": "Press",    "desc": "Breaking News RDC — French/English DRC conflict updates"},
            {"handle": "@MONUSCO",       "url": "https://x.com/MONUSCO",       "type": "NGO / UN", "desc": "UN peacekeeping mission — eastern DRC security and movement updates"},
            {"handle": "@trtafrika",     "url": "https://x.com/trtafrika",     "type": "Press",    "desc": "TRT Afrika — regional Africa conflict and politics coverage"},
            {"handle": "@AfricaCDC",     "url": "https://x.com/AfricaCDC",     "type": "NGO / UN", "desc": "Africa CDC — disease outbreak and health crisis alerts across region"},
            {"handle": "@FelixUdps",       "url": "https://x.com/FelixUdps",       "type": "Government", "desc": "Félix Tshisekedi / UDPS — official presidential communications (FR)"},
            {"handle": "@life_Info_",      "url": "https://x.com/life_Info_",      "type": "Press",      "desc": "Life Info — DRC breaking news (FR)"},
            {"handle": "@VoiceOfCongo",    "url": "https://x.com/VoiceOfCongo",    "type": "Press",      "desc": "Voice of Congo — English-language DRC coverage"},
            {"handle": "@thetimesplus",    "url": "https://x.com/thetimesplus",    "type": "Press",      "desc": "The Times Plus — DRC and regional reporting"},
            {"handle": "@alternancecd",    "url": "https://x.com/alternancecd",    "type": "Press",      "desc": "Alternance CD — Congolese political reporting (FR)"},
            {"handle": "@mediacongo",      "url": "https://x.com/mediacongo",      "type": "Press",      "desc": "MediaCongo — DRC news aggregator (FR)"},
            {"handle": "@CACAP_NEWS",      "url": "https://x.com/CACAP_NEWS",      "type": "Press",      "desc": "CACAP News — Central Africa coverage (FR)"},
            {"handle": "@KongoMediaRDC",   "url": "https://x.com/KongoMediaRDC",   "type": "Press",      "desc": "Kongo Media RDC — local news (FR)"},
            {"handle": "@radiookapi",      "url": "https://x.com/radiookapi",      "type": "Press",      "desc": "Radio Okapi — UN-backed national broadcaster (FR)"},
            {"handle": "@rtncofficielle1", "url": "https://x.com/rtncofficielle1", "type": "Government", "desc": "RTNC — Congolese national broadcaster (FR)"},
        ],
        "instagram": [],
        "hashtags": ["#DRC", "#CongoWar", "#M23", "#EasternCongo", "#Ituri", "#NordKivu", "#CODECO"],
        "searchTerms": ["DRC M23 withdrawal", "Congo Ituri CODECO", "Goma conflict", "eastern Congo humanitarian"],
    },
    "Somalia": {
        "x": [
            {"handle": "@SomaliaNewsroom", "url": "https://x.com/SomaliaNewsroom", "type": "Press",            "desc": "Somalia Newsroom — independent security and conflict reporting"},
            {"handle": "@somalianews",     "url": "https://x.com/somalianews",     "type": "Press",            "desc": "Somalia News — aggregated breaking developments"},
            {"handle": "@SomaliFederalN",  "url": "https://x.com/SomaliFederalN",  "type": "Government",       "desc": "Somali Federal Network — official government communications"},
            {"handle": "@criticalthreats", "url": "https://x.com/criticalthreats", "type": "Conflict Monitor", "desc": "AEI Critical Threats — al-Shabaab operations tracking and analysis"},
            {"handle": "@SMSSomaliTV1",    "url": "https://x.com/SMSSomaliTV1",    "type": "Press",            "desc": "SMS Somali TV — broadcast news"},
            {"handle": "@Baidoaonline",    "url": "https://x.com/Baidoaonline",    "type": "Press",            "desc": "Baidoa Online — Southwest State local reporting"},
            {"handle": "@ADFmagazine",     "url": "https://x.com/ADFmagazine",     "type": "Conflict Monitor", "desc": "Africa Defense Forum — security and counterterrorism coverage"},
            {"handle": "@SomaliGuardian",  "url": "https://x.com/SomaliGuardian",  "type": "Press",            "desc": "Somali Guardian — independent security reporting (X feed)"},
            {"handle": "@Hornpostnews",    "url": "https://x.com/Hornpostnews",    "type": "Press",            "desc": "Horn Post News — Horn of Africa breaking updates"},
            {"handle": "@Eye_on_Somalia",  "url": "https://x.com/Eye_on_Somalia",  "type": "Conflict Monitor", "desc": "Eye on Somalia — al-Shabaab and AUSSOM tracking"},
            {"handle": "@DawanAfrica",     "url": "https://x.com/DawanAfrica",     "type": "Press",            "desc": "Dawan Africa — regional security and politics"},
            {"handle": "@SouthwestWatxh",  "url": "https://x.com/SouthwestWatxh",  "type": "Conflict Monitor", "desc": "Southwest Watch — Southwest State conflict monitoring"},
            {"handle": "@GaroweOnline",    "url": "https://x.com/GaroweOnline",    "type": "Press",            "desc": "Garowe Online — Puntland news"},
            {"handle": "@FrontierOnlineK", "url": "https://x.com/FrontierOnlineK", "type": "Press",            "desc": "Frontier Online Kenya — Somalia/Kenya border coverage"},
            {"handle": "@SONNALIVE",       "url": "https://x.com/SONNALIVE",       "type": "Government",       "desc": "SONNA Live — Somali National News Agency live feed"},
            {"handle": "@TheDailySomalia", "url": "https://x.com/TheDailySomalia", "type": "Press",            "desc": "The Daily Somalia — daily news roundups"},
            {"handle": "@AnalystSomalia",  "url": "https://x.com/AnalystSomalia",  "type": "Analyst",          "desc": "Somalia Analyst — independent political and security analysis"},
        ],
        "instagram": [],
        "hashtags": ["#Somalia", "#AlShabaab", "#Mogadishu", "#Shabaab", "#AUSSOM", "#SomaliaCrisis"],
        "searchTerms": ["al-Shabaab attack Somalia", "Mogadishu bombing", "Somalia AUSSOM", "al-Shabaab IED"],
    },
    "Ethiopia": {
        "x": [
            {"handle": "@EthiopianNewsA",  "url": "https://x.com/EthiopianNewsA",  "type": "Government",       "desc": "Ethiopian News Agency — official state media and government positions"},
            {"handle": "@EthiopiaNews3",   "url": "https://x.com/EthiopiaNews3",   "type": "Press",            "desc": "Ethiopia News — conflict and political developments"},
            {"handle": "@addisstandard",   "url": "https://x.com/addisstandard",   "type": "Press",            "desc": "Addis Standard — independent investigative Ethiopia journalism"},
            {"handle": "@AmharaWarUpdate", "url": "https://x.com/AmharaWarUpdate", "type": "Conflict Monitor", "desc": "Amhara War Update — real-time conflict tracking in Amhara region"},
            {"handle": "@ForeignAffairs",  "url": "https://x.com/ForeignAffairs",  "type": "Analyst",          "desc": "Foreign Affairs — policy analysis and Horn of Africa strategic context"},
            {"handle": "@TheReporterET",   "url": "https://x.com/TheReporterET",   "type": "Press",            "desc": "The Reporter Ethiopia (X feed) — independent Ethiopia journalism"},
            {"handle": "@EthiopiaInsight", "url": "https://x.com/EthiopiaInsight", "type": "Analyst",          "desc": "Ethiopia Insight — long-form analysis on Ethiopian politics and conflict"},
            {"handle": "@PMEthiopia",      "url": "https://x.com/PMEthiopia",      "type": "Government",       "desc": "Office of the Prime Minister of Ethiopia — official communications"},
            {"handle": "@EthioReporter",   "url": "https://x.com/EthioReporter",   "type": "Press",            "desc": "Ethio Reporter — news and political coverage"},
        ],
        "instagram": [],
        "hashtags": ["#Ethiopia", "#Tigray", "#TPLF", "#Amhara", "#OLA", "#EthiopiaCrisis", "#PretoriaAgreement"],
        "searchTerms": ["Ethiopia TPLF clashes 2026", "Tigray government Pretoria", "Amhara TDF fighting", "Ethiopia Oromia OLA"],
    },
    "Regional": {
        "x": [
            {"handle": "@theEastAfrican", "url": "https://x.com/theEastAfrican", "type": "Press",    "desc": "The East African — regional politics, security, and business across East Africa"},
            {"handle": "@ifrc",           "url": "https://x.com/ifrc",           "type": "NGO / UN", "desc": "IFRC — International Federation of Red Cross humanitarian alerts and operations"},
            {"handle": "@WIONews",        "url": "https://x.com/WIONews",        "type": "Press",    "desc": "WIO News — West Indian Ocean regional news covering East & Central Africa"},
            {"handle": "@cgtnafrica",     "url": "https://x.com/cgtnafrica",     "type": "Press",    "desc": "CGTN Africa — pan-African news coverage including conflict and politics"},
            {"handle": "@AfticaCDC",      "url": "https://x.com/AfticaCDC",      "type": "NGO / UN", "desc": "Africa CDC (alt handle) — regional disease outbreak and health emergency alerts"},
            {"handle": "@BBCAfrica",      "url": "https://x.com/BBCAfrica",      "type": "Press",    "desc": "BBC Africa — breaking news and investigations across the continent"},
            {"handle": "@CrisisGroup",    "url": "https://x.com/CrisisGroup",    "type": "Analyst",  "desc": "International Crisis Group — conflict analysis and early warning across East Africa"},
            {"handle": "@africaupdates",  "url": "https://x.com/africaupdates",  "type": "Press",    "desc": "Africa Updates — pan-African breaking news aggregator"},
            {"handle": "@_AfricanUnion",  "url": "https://x.com/_AfricanUnion",  "type": "Government","desc": "African Union — continental policy, peace and security communications"},
            {"handle": "@jeune_afrique",  "url": "https://x.com/jeune_afrique",  "type": "Press",    "desc": "Jeune Afrique — francophone Africa politics and security"},
            {"handle": "@RFI",            "url": "https://x.com/RFI",            "type": "Press",    "desc": "Radio France Internationale — global francophone news coverage"},
            {"handle": "@AfricaViewFacts","url": "https://x.com/AfricaViewFacts","type": "Analyst",  "desc": "Africa View Facts — data-driven African affairs commentary"},
            {"handle": "@ThomasVLinge",   "url": "https://x.com/ThomasVLinge",   "type": "Conflict Monitor","desc": "Thomas van Linge — conflict mapping and OSINT (Sudan/Ethiopia)"},
            {"handle": "@LarryMadowo",    "url": "https://x.com/LarryMadowo",    "type": "Press",    "desc": "Larry Madowo — CNN International Africa correspondent"},
            {"handle": "@Lattif",         "url": "https://x.com/Lattif",         "type": "Analyst",  "desc": "Lattif — Horn of Africa security analyst"},
            {"handle": "@samirasawlani",  "url": "https://x.com/samirasawlani",  "type": "Analyst",  "desc": "Samira Sawlani — East Africa journalist and analyst"},
            {"handle": "@johnnallannamu", "url": "https://x.com/johnnallannamu", "type": "Press",    "desc": "John-Allan Namu — investigative journalist (Africa Uncensored)"},
            {"handle": "@Afuncensored",   "url": "https://x.com/Afuncensored",   "type": "Press",    "desc": "Africa Uncensored — investigative outlet covering East/Central Africa"},
            {"handle": "@Nairobi_News",   "url": "https://x.com/Nairobi_News",   "type": "Press",    "desc": "Nairobi News — Kenyan and regional updates"},
            {"handle": "@Kalinaki",       "url": "https://x.com/Kalinaki",       "type": "Analyst",  "desc": "Daniel Kalinaki — East Africa columnist and analyst"},
            {"handle": "@JewelKiriungi",  "url": "https://x.com/JewelKiriungi",  "type": "Press",    "desc": "Jewel Kiriungi — Africa correspondent"},
            {"handle": "@bella_twine",    "url": "https://x.com/bella_twine",    "type": "Press",    "desc": "Bella Twine — Africa news commentary"},
            {"handle": "@WorldBankAfrica","url": "https://x.com/WorldBankAfrica","type": "NGO / UN", "desc": "World Bank Africa — development and economic stability updates"},
        ],
        "instagram": [],
        "hashtags": ["#EastAfrica", "#HornOfAfrica", "#AfricaNews", "#RegionalSecurity"],
        "searchTerms": ["East Africa security", "Horn of Africa crisis", "Africa regional conflict"],
    },
}
